# Generated by Django 4.2.7 on 2025-11-27 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('lunch_time', models.TimeField()),
                ('is_off', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LunchAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.employee')),
            ],
        ),
        migrations.CreateModel(
            name='WorkRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('max_start_time', models.TimeField(default='11:00')),
                ('min_end_time', models.TimeField(default='17:00')),
                ('max_end_time', models.TimeField(default='20:00')),
                ('work_hours', models.IntegerField(default=8)),
                ('lunch_duration', models.IntegerField(default=60)),
            ],
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)])),
                ('year', models.IntegerField(choices=[(2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027), (2028, 2028), (2029, 2029), (2030, 2030)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='TimeOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.employee')),
            ],
        ),
        migrations.CreateModel(
            name='ShiftSwapRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_date', models.DateField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('original_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original_swap_requests', to='timetable.dailyschedule')),
                ('requested_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_requests_received', to='timetable.employee')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_requests_made', to='timetable.employee')),
            ],
        ),
        migrations.CreateModel(
            name='LunchSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_slot', models.TimeField()),
                ('max_people', models.IntegerField(default=5)),
                ('employees', models.ManyToManyField(through='timetable.LunchAssignment', to='timetable.employee')),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lunch_schedules', to='timetable.timetable')),
            ],
            options={
                'ordering': ['date', 'time_slot'],
                'unique_together': {('timetable', 'date', 'time_slot')},
            },
        ),
        migrations.AddField(
            model_name='lunchassignment',
            name='lunch_schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.lunchschedule'),
        ),
        migrations.AddField(
            model_name='dailyschedule',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.employee'),
        ),
        migrations.AddField(
            model_name='dailyschedule',
            name='replacement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacements', to='timetable.employee'),
        ),
        migrations.AddField(
            model_name='dailyschedule',
            name='timetable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_schedules', to='timetable.timetable'),
        ),
        migrations.AlterUniqueTogether(
            name='lunchassignment',
            unique_together={('lunch_schedule', 'employee')},
        ),
        migrations.CreateModel(
            name='EmployeeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_start_time', models.TimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.employee')),
                ('work_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.workrule')),
            ],
            options={
                'unique_together': {('employee', 'work_rule')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='dailyschedule',
            unique_together={('timetable', 'employee', 'date')},
        ),
    ]
