# Generated by Django 4.2.7 on 2025-11-27 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_alter_employee_options_employee_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodPickupAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FoodPickupSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('max_people', models.IntegerField(default=2)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='lunchschedule',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='lunchschedule',
            name='employees',
        ),
        migrations.RemoveField(
            model_name='lunchschedule',
            name='timetable',
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['name'], 'permissions': [('manage_all', 'Can manage all timetable operations'), ('view_personal_schedule', 'Can view personal schedule'), ('request_shift_swap', 'Can request shift swaps')]},
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], default='inbound', max_length=20),
        ),
        migrations.DeleteModel(
            name='LunchAssignment',
        ),
        migrations.DeleteModel(
            name='LunchSchedule',
        ),
        migrations.AddField(
            model_name='foodpickupschedule',
            name='assigned_employees',
            field=models.ManyToManyField(related_name='food_pickup_assignments', through='timetable.FoodPickupAssignment', to='timetable.employee'),
        ),
        migrations.AddField(
            model_name='foodpickupschedule',
            name='timetable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_pickups', to='timetable.timetable'),
        ),
        migrations.AddField(
            model_name='foodpickupassignment',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.employee'),
        ),
        migrations.AddField(
            model_name='foodpickupassignment',
            name='food_pickup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.foodpickupschedule'),
        ),
        migrations.AlterUniqueTogether(
            name='foodpickupschedule',
            unique_together={('timetable', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='foodpickupassignment',
            unique_together={('food_pickup', 'employee')},
        ),
    ]
