# Generated by Django 4.2.7 on 2025-11-28 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timetable', '0003_foodpickupassignment_foodpickupschedule_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shiftswaprequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='shiftswaprequest',
            name='employee_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shiftswaprequest',
            name='employee_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shiftswaprequest',
            name='manager_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shiftswaprequest',
            name='manager_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shiftswaprequest',
            name='manager_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_swaps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shiftswaprequest',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='timeoff',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_time_off', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shiftswaprequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_approved_swaps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shiftswaprequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('manager_approved', 'Manager Approved'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='SwapHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('swap_date', models.DateField()),
                ('original_schedule_data', models.JSONField()),
                ('target_schedule_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('original_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original_swaps', to='timetable.employee')),
                ('swap_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.shiftswaprequest')),
                ('target_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_swaps', to='timetable.employee')),
            ],
            options={
                'ordering': ['-swap_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('department_access', models.CharField(choices=[('all', 'All Departments'), ('inbound', 'Inbound Only'), ('outbound', 'Outbound Only')], default='all', max_length=20)),
                ('can_approve_swaps', models.BooleanField(default=True)),
                ('can_manage_employees', models.BooleanField(default=True)),
                ('can_generate_timetables', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
