# Generated by Django 4.2.7 on 2025-11-28 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_alter_shiftswaprequest_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manager',
            options={'ordering': ['name'], 'verbose_name': 'Manager', 'verbose_name_plural': 'Managers'},
        ),
    ]
