# Generated by Django 4.2.7 on 2025-11-29 09:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0005_alter_manager_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyschedule',
            name='is_auto_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='timetable',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
